jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [android, ios]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Set Expo token
        run: echo "EXPO_TOKEN is set"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Dev Client
        run: eas build --platform ${{ matrix.platform }} --profile development --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
