name: EAS Dev Client Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install EAS CLI
        run: npm install -g eas-cli expo-cli

      - name: Install dependencies
        run: npm install

      - name: Run Expo Prebuild (Android only)
        run: npx expo prebuild --platform android --non-interactive

      - name: Reinstall Dependencies After Prebuild
        run: npm install

      - name: Build Dev Client (Android)
        run: eas build --platform android --profile development --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
